language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install:
  - "pip install Lektor"
  - "rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 0.12"

script: "lektor build -f webpack"
deploy:
  provider: script
  skip_cleanup: true
  script: "lektor deploy ghpages-https"
  on:
    branch: master

