language: python
python: 2.7
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
install: "pip install Lektor"
script: "lektor build"
deploy:
  provider: script
  skip_cleanup: true
  script: "lektor deploy ghpages-https"
  on:
    branch: master

